upstream jwta { server 127.0.0.1:4041; }

server {
    listen 443 ssl;
    server_name jwta.pqtr.ai;

    ssl_certificate /etc/letsencrypt/live/jwta.pqtr.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jwta.pqtr.ai/privkey.pem;

    client_max_body_size 8k;
    limit_req zone=jwta burst=5 nodelay;

    location /jrpc {
        proxy_pass http://jwta;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /boot {
        proxy_pass http://jwta;
    }
}
