# Makefile.wasm - Build LABS login for WebAssembly
#
# Requires: Emscripten SDK
#   git clone https://github.com/emscripten-core/emsdk.git
#   cd emsdk && ./emsdk install latest && ./emsdk activate latest
#   source emsdk_env.sh
#
# Build: make -f Makefile.wasm
# Output: tmp/wasm/labs.html, labs.js, labs.wasm

IMGUI = lib/imgui

SRC = src/wasm/login.cpp \
      $(IMGUI)/imgui.cpp \
      $(IMGUI)/imgui_draw.cpp \
      $(IMGUI)/imgui_tables.cpp \
      $(IMGUI)/imgui_widgets.cpp \
      $(IMGUI)/backends/imgui_impl_glfw.cpp \
      $(IMGUI)/backends/imgui_impl_opengl3.cpp

INC = -I$(IMGUI) -I$(IMGUI)/backends

# Emscripten flags (requires emsdk 4.x - run: source env.sh)
EMFLAGS = --use-port=contrib.glfw3 \
          -sUSE_WEBGL2=1 \
          -sFULL_ES3=1 \
          -sWASM=1 \
          -sALLOW_MEMORY_GROWTH=1 \
          -sNO_EXIT_RUNTIME=0 \
          -sASSERTIONS=1 \
          -sFETCH

# Shell template (custom HTML)
SHELL_TPL = --shell-file src/wasm/shell.html

OUT = tmp/wasm

.PHONY: all clean deploy

all: $(OUT)/labs.js $(OUT)/labs.html

$(OUT)/labs.js: $(SRC) | $(OUT)
	emcc $(SRC) $(INC) $(EMFLAGS) -O2 -o $@

$(OUT)/labs.html: src/wasm/shell.html $(OUT)/labs.js
	sed 's|{{{ SCRIPT }}}|<script src="labs.js?v=$(shell date +%s)"></script>|' $< > $@

$(OUT):
	mkdir -p $(OUT)

clean:
	rm -rf $(OUT)

# Deploy to BASE/www
deploy: all
	cp $(OUT)/labs.html $(OUT)/labs.js $(OUT)/labs.wasm ../BASE/www/
	@echo "Deployed to BASE/www/"
