// colorin.cpp - Camera RGB → XYZ(D50) → Lab
//
// Matches darktable's colorin module for STANDARD_MATRIX profile.
// Uses pre-computed cam→XYZ(D50) matrix (Bradford D65→D50 already applied).

#include "../../../inc/pipe.hpp"
#include <cmath>

namespace flow
{

// D50 white point (standard for Lab)
static constexpr float D50_X = 0.9642f;
static constexpr float D50_Y = 1.0000f;
static constexpr float D50_Z = 0.8249f;

// Pre-computed cam→XYZ(D50) matrix for Sony ILCE-7M3
// Generated by LCMS2 from LibRaw cam_xyz matrix, exactly as DT does.
// Source: colorin_matrix.cpp reads LCMS profile colorant tags.
// Verification: (1,1,1) → (0.9642, 1.0, 0.8249) = D50 white ✓
static constexpr float CAM_TO_XYZ_D50_ILCE7M3[9] = {
     0.66432885f,  0.35009432f, -0.05022317f,
     0.27061894f,  0.98668630f, -0.25730524f,
     0.01820291f, -0.15562350f,  0.96232059f
};

// Fast cube root approximation (from DT colorspaces_inline_conversions.h)
static inline float cbrt_5f(float f)
{
    uint32_t* p = (uint32_t*)&f;
    *p = *p / 3 + 709921077;
    return f;
}

// Halley's method refinement (from DT)
static inline float cbrta_halleyf(float a, float R)
{
    const float a3 = a * a * a;
    const float b = a * (a3 + R + R) / (a3 + a3 + R);
    return b;
}

// Lab f() function - CLEAN COPY from DT colorspaces_inline_conversions.h:160
static inline float lab_f(float x)
{
    const float epsilon = 216.0f / 24389.0f;
    const float kappa = 24389.0f / 27.0f;
    return (x > epsilon) ? cbrta_halleyf(cbrt_5f(x), x) : (kappa * x + 16.0f) / 116.0f;
}

class ColorinImpl : public Colorin
{
public:
    std::string name() const override { return "colorin"; }
    std::string save() override { return "{}"; }
    void load(const std::string&) override {}

    void process(Flow& flow) override
    {
        auto& root = flow.info().root();

        int width = static_cast<int>(root.leaf(WIDTH).dial());
        int height = static_cast<int>(root.leaf(HEIGHT).dial());
        size_t npixels = static_cast<size_t>(width) * height;

        // Use pre-computed matrix (cam→XYZ D50) for ILCE-7M3
        // This matrix maps camera (1,1,1) to D50 white point
        const float* M = CAM_TO_XYZ_D50_ILCE7M3;

        float* rgb = flow.rgb();

        // Process each pixel: camera RGB → XYZ D50 → Lab
        for (size_t i = 0; i < npixels; i++)
        {
            size_t idx = i * 4;
            float r = rgb[idx + 0];
            float g = rgb[idx + 1];
            float b = rgb[idx + 2];

            // Camera RGB → XYZ D50 (single matrix, already adapted)
            float X = M[0] * r + M[1] * g + M[2] * b;
            float Y = M[3] * r + M[4] * g + M[5] * b;
            float Z = M[6] * r + M[7] * g + M[8] * b;

            // XYZ D50 → Lab
            float fx = lab_f(X / D50_X);
            float fy = lab_f(Y / D50_Y);
            float fz = lab_f(Z / D50_Z);

            float L = 116.0f * fy - 16.0f;
            float a = 500.0f * (fx - fy);
            float bval = 200.0f * (fy - fz);

            // Store Lab in rgb buffer (reusing same memory)
            rgb[idx + 0] = L;
            rgb[idx + 1] = a;
            rgb[idx + 2] = bval;
        }
    }
};

std::unique_ptr<Colorin> makeColorin()
{
    return std::make_unique<ColorinImpl>();
}

} // namespace flow
